---
title: "Quant Bootcamp - Module 1"
format: html
---

### About CPC

Founded in 2014, CPC Analytics is a data-driven public policy consulting firm. It has offices in Berlin & Pune. 

Bringing together qualitative and quantitative research methods, CPC’s team of economists, social scientists, and software engineers support public sector organizations and businesses to undertake policy research and collect, analyze and visualize data. 

[Website](www.cpc-analytics.com)

### What is Quant Bootcamp

As people in the social science space increasingly rely on evidence-based strategies to address societal challenges, the need for social scientists who are proficient in both qualitative and quantitative methodologies has never been more apparent. 
 
Traditionally, social scientists have tended to specialize in either qualitative or quantitative methods. While qualitative research provides rich insights, quantitative analysis offers the rigor and evidence necessary for making informed decisions and policy recommendations. To bridge this gap, CPC Analytics’ Quant Bootcamp 2024 is designed in such a way that will equip participants with relevant data analysis skills.

Welcome to Module 1 of Quant Bootcamp! The aim of organising this module to introduce participants to R and basics of data wrangling and data visualization in R

### Installing R

You can install RStudio from [this](https://posit.co/download/rstudio-desktop/) link

### Resources

**Day 1**

 + Slides(Quant_Bootcamp_D1.html)
 + Exercises 1(Exercise1.html)
 + Exercises 2(Exercise2.html)
 
**Day 2**

 + Slides
 + Exercises 1
 + Exercises 2